[package]
name = "celestial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.26.2"
pollster = "0.3.0"
thiserror = "1.0.58"
wgpu = "0.19.3"
winit = "0.29.15"
